name: universal_glass
description: "A reusable Flutter glassmorphism UI component library."

version: 2.1.2

homepage: https://github.com/afirinterfacedrive-creator/glass
repository: https://github.com/afirinterfacedrive-creator/glass

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  shared_preferences: ^2.3.5
  flutter_colorpicker: ^1.1.0
  path_provider: ^2.1.3
  share_plus: ^12.0.2
  file_picker: ^11.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/phone/phone_countries.json
    - assets/phone/flags/
    - assets/noise.png
    - assets/noise_dark.png
    - assets/phone/phone_operators.json